source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
target 'CommunityProject' do
pod 'AFNetworking','~> 3.0'
pod 'MJRefresh','~> 3.1.12'
pod 'JSONModel'
pod 'SDWebImage', '~> 3.8.2'
pod 'FMDB', '~> 2.6.2'
pod 'RongCloudIM/IMKit','~>2.8.4'
pod 'RongCloudIM/IMLib','~>2.8.4'
pod 'RongCloudIM/CallLib','~>2.8.4'
pod 'RongCloudIM/CallKit','~>2.8.4'
pod 'RongCloudIM/RedPacket','~>2.8.4'
pod 'Masonry', '~> 1.0.2'
pod 'SDCycleScrollView','~> 1.65'
end

