source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
target 'CommunityProject' do
pod 'AFNetworking','~> 3.0'
pod 'MJRefresh','~> 3.1.12'
pod 'JSONModel'
pod 'SDWebImage', '~> 3.8.2'
pod 'FMDB', '~> 2.6.2'
pod 'Masonry', '~> 1.0.2'
pod 'SDCycleScrollView','~> 1.65'
pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
pod 'CTAssetsPickerController',  '~> 3.3.0'
end

